version: '3'
services:
  api:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
     - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./.db:/data/db
    ports:
      - "27018:27017"
