version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - client
    ports:
     - "${CLIENT_PORT:-80}:80"
  client:
    build: ./client
    environment:
      - API_URI=http://api:3000
    command: [ "npm", "run", "${CLIENT_NPM_CMD:-build}" ]
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
     - "${DEV_PORT:-3001}:3001"
    depends_on:
      - api
  api:
    build: ./server
    environment:
      - MONGO_URI=mongodb://db:27017/getmobit
      - REDIS_URI=redis://redis:6379
    command: [ "npm", "run", "${SERVER_NPM_CMD:-start}" ]
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
     - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: mongo
    volumes:
      - ./.db:/data/db
    ports:
      - "27018:27017"
  redis:
    image: redis
    ports:
      - "6380:6379"
