version: '3'
services:
  api:
    build: ./server
    command: [ "npm", "run", "${SERVER_NPM_CMD:-start}" ]
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
     - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./.db:/data/db
    ports:
      - "27018:27017"
